[package]
name = "hdf5-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.52.0"
ndarray = "0.15.4"
hdf5 = "0.8.1"
tokio = { version = "1", features = ["full"] }
